version: 2.1
jobs:
  build:
    working_directory: ~/immutability
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: 
          name: "Build and test" 
          command: |
            make all
          no_output_timeout: 2400

  publish_immutability:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      IMMUTABILITY_IMAGE_NAME: "omisego/immutability-eth-plugin"
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: make docker-childchain IMMUTABILITY_IMAGE_NAME=$IMMUTABILITY_IMAGE_NAME
      - run: IMAGE_NAME=$IMMUTABILITY_IMAGE_NAME sh .circleci/ci_publish.sh

workflows:
  version: 2
  build-test-lint:
    jobs:
      - build
      - publish_immutability:
          requires:
            [
              build
            ]
          filters: &master_and_version_branches_and_all_tags
            branches:
              only:
                - master
                # vMAJOR.MINOR (e.g. v0.1, v0.2, v1.0, v2.1, etc.)
                - /^v[0-9]+\.[0-9]+/
            tags:
              only:
                - /.+/